// @ts-nocheck
import React from "react";
import { Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer";

const styles = StyleSheet.create({
  page: {
    padding: 40,
    fontFamily: "Helvetica",
    color: "#1a1a1a",
  },
  header: {
    marginBottom: 28,
    paddingBottom: 16,
    borderBottomWidth: 2,
    borderBottomColor: "#2563eb",
  },
  brand: {
    fontSize: 22,
    fontWeight: "bold",
    color: "#2563eb",
  },
  subtitle: {
    marginTop: 4,
    fontSize: 10,
    color: "#64748b",
  },
  title: {
    marginBottom: 22,
    fontSize: 19,
    fontWeight: "bold",
  },
  row: {
    flexDirection: "row",
    borderBottomWidth: 1,
    borderBottomColor: "#e2e8f0",
    paddingVertical: 12,
  },
  label: {
    width: 170,
    fontSize: 10,
    color: "#64748b",
  },
  value: {
    flex: 1,
    fontSize: 11,
  },
  score: {
    marginTop: 28,
    padding: 18,
    backgroundColor: "#eff6ff",
    borderWidth: 1,
    borderColor: "#bfdbfe",
  },
  scoreLabel: {
    fontSize: 10,
    color: "#1d4ed8",
  },
  scoreValue: {
    marginTop: 6,
    fontSize: 25,
    fontWeight: "bold",
    color: "#1e3a8a",
  },
  footer: {
    marginTop: 42,
    paddingTop: 14,
    borderTopWidth: 1,
    borderTopColor: "#e2e8f0",
    fontSize: 9,
    color: "#94a3b8",
    textAlign: "center",
  },
});

interface AssessmentResultPDFProps {
  assessmentName: string;
  score: number;
  date: string;
  freelancerName: string;
  passingThreshold: number;
}

export const AssessmentResultPDF: React.FC<AssessmentResultPDFProps> = ({
  assessmentName,
  score,
  date,
  freelancerName,
  passingThreshold,
}) => (
  <Document>
    <Page size="A4" style={styles.page}>
      <View style={styles.header}>
        <Text style={styles.brand}>MarketPay</Text>
        <Text style={styles.subtitle}>Verified assessment result</Text>
      </View>

      <Text style={styles.title}>{assessmentName}</Text>

      <View style={styles.row}>
        <Text style={styles.label}>Freelancer</Text>
        <Text style={styles.value}>{freelancerName}</Text>
      </View>
      <View style={styles.row}>
        <Text style={styles.label}>Assessment date</Text>
        <Text style={styles.value}>{date}</Text>
      </View>
      <View style={styles.row}>
        <Text style={styles.label}>Passing threshold</Text>
        <Text style={styles.value}>{passingThreshold}%</Text>
      </View>

      <View style={styles.score}>
        <Text style={styles.scoreLabel}>Final score</Text>
        <Text style={styles.scoreValue}>{score}%</Text>
      </View>

      <Text style={styles.footer}>
        This document was generated by MarketPay.
      </Text>
    </Page>
  </Document>
);